apps/login_reg/urls.py
from django.conf.urls import url
# from . import views
from views import index, login, register, logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login$', login, name='login'),
    url(r'^register$', register, name='register'),
    # url(r'^success$', success, name='success'),
    url(r'^logout$', logout, name='logout'),
]

blackbelt1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_reg.urls', namespace='user_con')),
    url(r'^wishlist/', include('apps.wishlist.urls', namespace='wishlist')),
]

apps/login_reg/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from datetime import datetime
import re, bcrypt

name_regex = re.compile(r"^[a-zA-Z\-]+$")
# EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):

    def loginValidate(self, request):
        try:
            user = User.objects.get(user_name=request.POST['user_name'])
            password = request.POST['password'].encode()
            hashed_pw = user.pw_hash.encode()
            print user
            print password
            print hashed_pw

            if hashed_pw == bcrypt.hashpw(password, hashed_pw):
                return (True, user)

        except ObjectDoesNotExist:
            print("A user by that User Name does not exist.")
            pass

        return (False, ["Incorrect User Name/Email, or the User does not exist."])

    def regValidate(self, request):
        errors = []
        # hire_date = datetime.strptime(request.POST['hire_date'], '%Y-%m-%d')

        # if User.objects.filter(user_name=request.POST['user_name'].strip().lower()):
        if User.objects.filter(user_name=request.POST['user_name']):
            errors.append("A user with that User Name already exists!  Please Log In.")

        if len(request.POST['first_name']) < 3:
            errors.append("The First Name field cannot be blank! It must each have at least 3 characters.")

        elif not name_regex.match(request.POST['first_name']):
            errors.append("You may not include any numbers or special characters in the First Name.")

        if len(request.POST['user_name']) < 3:
            errors.append("The User Name field cannot be blank! It must each have at least 3 characters.")

        if len(request.POST['password']) < 8:
            errors.append('Your Password must contain 8 or more characters!')

        if request.POST['password'] != request.POST['confirm_pw']:
            errors.append('Your Password and Confirm Password must match!')

        if len(request.POST['hire_date']) >= 0:
            try:
                strp_hire_date = datetime.strptime(request.POST['hire_date'], '%Y-%m-%d')
                print "Stripped The Time"
            except:
                # strp_hire_date = datetime.strptime(request.POST['hire_date'], '%Y-%m-%d')
                errors.append('Please enter the valid date you were Hired on.')

        if errors:
            return(False, errors)

        #Create the PW Hash if no errors
        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        print pw_hash

        #Create New User once the PW is hashed
        # strp_hire_date = datetime.strptime(request.POST['hire_date'], '%Y-%m-%d')
        user = self.create(first_name=request.POST['first_name'], user_name=request.POST['user_name'], pw_hash=pw_hash, hire_date=strp_hire_date)
        print "created a user, at last"
        return (True, user)

class User(models.Model):
    # item = models.ForeignKey(Item)
    first_name = models.CharField(max_length=50)
    user_name = models.CharField(max_length=50)
    pw_hash = models.CharField(max_length=256)
    hire_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/login_reg/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from models import User
# from datetime import datetime

# Create your views here.
def index(request):
    return render(request, 'login_reg/index.html')

def login(request):
    result = User.objects.loginValidate(request)

    if result[0] == False:
        show_messages(request, result[1])
        return redirect(reverse('user_con:index'))

    return log_in_user(request, result[1])

def register(request):
    result = User.objects.regValidate(request)

    if result[0] == False:
        show_messages(request, result[1])
        return redirect(reverse('user_con:index'))

    return log_in_user(request, result[1])

# def success(request):
#     if not 'user' in request.session:
#         return redirect(reverse('user_con:index'))
#     ##Success brings user to the Wishlist section
#     return render(request, 'wishlist/index.html')
#     # return render(request, 'login_reg/success.html')

def show_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

def log_in_user(request, user):
    request.session['user'] = {
        'id': user.id,
        'first_name': user.first_name,
        'user_name': user.user_name,
        # 'hire_date': user.hire_date,
    }
    return redirect(reverse('wishlist:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('user_con:index'))

apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login And Registration</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  </head>
  <body>
    <h1>Wish List</h1>
    <p>Please Log In or Register to continue.</p>
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
    {% endif %}
    <div id="login">
      <h2>Login</h2>
      <form action="{% url 'user_con:login' %}" method="post">
        {% csrf_token %}
        User Name: <input type="text" name="user_name" placeholder="User Name (Case Sensitive)">
        Password: <input type="password" name="password" placeholder="password">
        <input class="buttons" type="submit" value="Login">
      </form>
    </div>
    <p>Not registered yet?  Please Register below!</p>
    <div id="registration">
      <h2>Register</h2>
      <form action="{% url 'user_con:register' %}" method="post">
        {% csrf_token %}
        First Name: <input type="text" name="first_name" placeholder="First Name">
        User Name: <input type="text" name="user_name" placeholder="User Name (Case Sensitive)">
        Password: <input type="password" name="password" placeholder="password (8+ characters)">
        Confirm Password: <input type="password" name="confirm_pw" placeholder="Confirm (Must match Password)">
        Date Hired: <input type="date" name="hire_date" max="" value="" placeholder="YEAR-MO-DY">
        <input class="buttons" type="submit" value="Register">
      </form>
    </div>
  </body>
</html>

apps/login_reg/templates/login_reg/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success!!</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  </head>
  <body>
    <h1>Hello {{request.session.user.user_name}}!  You are now logged in.</h1>
    <div id="links">
      <div class="ninja">
        <a href="{% url 'wishlist:index' %}">Manage Your Wishlist</a>
      </div>
      <a href="{% url 'user_con:logout' %}">Logout</a>
    </div>
  </body>
</html>