apps/login_reg/urls.py
from django.conf.urls import url
# from . import views
from views import index, login, register, logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login$', login, name='login'),
    url(r'^register$', register, name='register'),
    # url(r'^success$', success, name='success'),
    url(r'^logout$', logout, name='logout'),
]

apps/wishlist/urls.py
from django.conf.urls import url
from views import users, users_w_id, new, destroy, add, remove


urlpatterns = [
    url(r'^$', users, name='index'),
    url(r'^new$', new, name='new'),
    url(r'^add(?P<item_id>\d+)$', add, name='add'),
    url(r'^remove(?P<item_id>\d+)$', remove, name='remove'),
    url(r'^(?P<id>\d+)/$', users_w_id),
    # url(r'^delete/(?P<item_id>\d+)$', destroy, name='destroy'),
    url(r'^(?P<id>\d+)/destroy/$', destroy, name='destroy'),
]

blackbelt1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_reg.urls', namespace='user_con')),
    url(r'^wishlist/', include('apps.wishlist.urls', namespace='wishlist')),
]

apps/wishlist/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.timezone import now
from ..login_reg.models import User

class ItemManager(models.Manager):

    def validItem(self, request):
        errors = []

        if Item.objects.filter(itm=request.POST['itm']):
            errors.append("That Item already exists!")

        if len(request.POST['itm']) < 4:
            errors.append("The Item field may not be left blank and must contain at least 4 characters.")

        if errors:
            return(False, errors)

        curr_user = User.objects.get(id=request.session['user']['id'])

        item = self.create(creator=curr_user, itm=request.POST['itm'], addby=request.POST['addby'], dateadd=request.POST['dateadd'])

        return (True, item)

    def fetch_item_users(self, item_id):
        print "banana"
        item_id = int(item_id)
        item = self.get(id=item_id)
        users = item.users.all()
        return (item, users)

    def remove_item(self, user_id, item_id):
        int(item_id)
        # get user and itms to remove
        try:
            user = User.objects.get(id=user_id)
            item = self.get(id=item_id)
            item.users.remove(user)
            return True
        except:
            return False

    def add_item(self, user_id, item_id):
        int(item_id)
        # get user and items to add
        try:
            user = User.objects.get(id=user_id)
            item = self.get(id=item_id)
            item.users.add(user)
            return True
        except:
            return False

    def get_my_items(self, user_id):
        items = self.filter(users__id=user_id)
        return items

    def get_other_items(self, user_id):
        items = self.exclude(users__id=user_id)
        return items


    def update(self, id, form_info):
        item = Item.objects.get(id=id)
        item.itm = form_info['itm']
        item.addby = form_info['addby']
        item.dateadd = form_info['dateadd']
        item.save()


class Item(models.Model):
    users = models.ManyToManyField(User, related_name="items")
    creator = models.ForeignKey(User)
    itm = models.CharField(max_length=45)
    addby = models.CharField(max_length=200)
    dateadd = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ItemManager()

apps/wishlist/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from models import Item
from ..login_reg.models import User


def users(request):
    if 'user' in request.session:
        if request.method == "POST":
            return create(request)
        print "got here"
        return index(request)
    else:
        return redirect(reverse('user_con:index'))

def users_w_id(request, id):
    if 'user' in request.session:
        if request.method == "POST":
            return update(request, id)
        return show(request, id)
    else:
        return redirect(reverse('user_con:index'))

def index(request):
    # Retrieve all items to display in template
    if 'user' in request.session:
        # items = Item.objects.all()
        context = {
            'my_items': Item.objects.get_my_items(request.session['user']['id']),
            'other_items': Item.objects.get_other_items(request.session['user']['id']),
        }
        return render(request, 'wishlist/index.html', context)
    else:
        return redirect(reverse('user_con:index'))

# POST /users
def create(request):
    if 'user' in request.session:
        result = Item.objects.validItem(request)

        if result[0] == False:
            show_messages(request, result[1])
            print "blargggg failed to create item"
            return redirect(reverse('wishlist:new'))
        print "made an item, yeahhhh"
        return redirect('/wishlist')
    else:
        return redirect(reverse('user_con:index'))

# GET /users/new  uses new.html to then create an item
def new(request):
    if 'user' in request.session:
        return render(request, 'wishlist/new.html')
    else:
        return redirect(reverse('user_con:index'))

#show validation messages on adding new item
def show_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

def show(request, item_id):
    if 'user' in request.session:
        item, users = Item.objects.fetch_item_users(item_id)
        context = {
            'users': users,
            'item_name': item.itm,
        }
        return render(request, 'wishlist/show.html', context)
    else:
        return redirect(reverse('user_con:index'))

def add(request, item_id):
    if 'user' in request.session:
        response = Item.objects.add_item(request.session['user']['id'], item_id)
        return redirect(reverse('wishlist:index'))
    else:
        return redirect(reverse('user_con:index'))

def remove(request, item_id):
    if 'user' in request.session:
        response = Item.objects.remove_item(request.session['user']['id'], item_id)
        return redirect(reverse('wishlist:index'))
    else:
        return redirect(reverse('user_con:index'))

def update(request, id):
    if 'user' in request.session:
        Item.objects.update(id, request.POST)
        return redirect('/wishlist')
    else:
        return redirect(reverse('user_con:index'))

# POST /users/<id>/destroy

def destroy(request, id):
    if 'user' in request.session:
        Item.objects.get(id=id).delete()
        print "Item DELETED!!!"
        return redirect('/wishlist')
    else:
        return redirect(reverse('user_con:index'))

# def destroy(request, item_id):
#     print "in destroy route"
#     if request.method == "POST":
#         print "post method True"
#         valid, response = Item.objects.delete_item(request.session['user']['id'], item_id)
#         if not valid:
#             for error in response:
#                 messages.error(request, error)
#     return redirect(reverse('wishlist:index'))

apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Wish List</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'wishlist/css/main.css' %}">
  </head>
  <body>
    <h1>Hello {{request.session.user.user_name}}!   You are now logged in.</h1>
    <a href="{% url 'user_con:logout' %}">Logout</a>
    <a href="/wishlist/new">Create a new Item!</a>
    <h3>Your Wish List</h3>
    {% if my_items %}
      <table>
        <thead>
          <tr>
            <th>Item</th>
            <th>Created by</th>
            <th>Date Added</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for item in my_items %}
          <tr>
            <td><a href="/wishlist/{{item.id}}/">{{item.itm}}</a></td>
            <td>{{item.addby}}</td>
            <td>{{item.dateadd}}</td>
            <td>
              <a href="{%  url 'wishlist:remove' item.id %}" value="remove">Remove Item</a>
              <form action="/wishlist/{{item.id}}/destroy/" method='post' class='delete'>
                {% csrf_token %}
                <input type="submit" value="Delete">
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>Your Wish List is currently empty.  You can either add items from the Items List below, or create a new Item!</p>
    {% endif %}

    <h3>Items List</h3>
    {% if other_items %}
      <table>
        <thead>
          <tr>
            <th>Item</th>
            <th>Created by</th>
            <th>Date Added</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for item in other_items %}
            <tr>
              <td><a href="/wishlist/{{item.id}}/">{{item.itm}}</a></td>
              <td>{{item.addby}}</td>
              <td>{{item.dateadd}}</td>
              <td>
                <a class="button" href="{%  url 'wishlist:add' item.id %}">Add This To My Wishlist!</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No Items have been added here yet.</p>
    {% endif %}
  </body>
</html>

apps/wishlist/templates/wishlist/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add new item</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'wishlist/css/styles.css' %}">
  </head>
  <body>
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
    {% endif %}
    <h2>Add a new item</h2>
    <form action="/wishlist/" method='post'>
      {% csrf_token %}
      Item: <input type="text" name="itm">
      <input type="hidden" value="{{request.session.user.user_name}}" name="addby">
      <input type="hidden" name="dateadd">
      <input type="submit" value="Create">
    </form>
    <a href="/wishlist">Go back</a>
  </body>
</html>

apps/wishlist/templates/wishlist/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Item details</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'wishlist/css/styles.css' %}">
  </head>
  <body>
    <h2>Item: {{ item_name }}</h2>
    <h4>Users who added this item in their Wish List</h4>
    {% for user in users %}
      <p>{{ user.user_name }}</p>
    {% empty %}
      <p>--No One has added this Item to their Wish List Yet!--</p>
    {% endfor %}
    <a href="/wishlist/">Back</a>
  </body>
</html>